apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: nested-agent
  namespace: kagent
spec:
  declarative:
    modelConfig: default-model-config
    stream: true
    systemMessage: |-
      You are a helpful assistant that can do anything.
      You can use the gh-server tool to interact with GitHub to find issues and pull requests.
      You can use the k8s-agent tool to get information about the cluster.
      You can use the helm-agent tool to manage helm releases.
    tools:
    - agent:
        apiGroup: kagent.dev
        kind: Agent
        name: helm-agent
      type: Agent
    - agent:
        apiGroup: kagent.dev
        kind: Agent
        name: k8s-agent
      type: Agent
    - mcpServer:
        apiGroup: kagent.dev
        kind: MCPServer
        name: gh-server
        toolNames:
        - list_pull_requests
        - get_pull_request
      type: McpServer
  description: This agent can do anything.
  type: Declarative

