apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: restrict-backend-policy
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app: backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        role: frontend   # Wrong label key
    toPorts:
    - ports:
      - port: "9090"
        protocol: TCP
