apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kagent-cilium-role
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: kagent
rules:
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  - ciliumclusterwidenetworkpolicies
  - ciliumendpoints
  - ciliumidentities
  - ciliumnodes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kagent-cilium-rolebinding
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: kagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kagent-cilium-role
subjects:
- kind: ServiceAccount
  name: kagent
  namespace: kagent
