kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: egress-gateway
  labels:
    app: egress-kgateway
spec:
  gatewayClassName: agentgateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: openai
spec:
  ai:
    provider:
      openai:
        model: "gpt-4.1-mini"
  policies:
    auth:
      secretRef:
        name: openai-secret
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openai
spec:
  parentRefs:
    - name: egress-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: openai
      group: gateway.kgateway.dev
      kind: AgentgatewayBackend
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: agw-model-config
  namespace: kagent
spec:
  model: gpt-4.1-mini
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  provider: OpenAI
  openAI:
    baseUrl: http://egress-gateway.default.svc.cluster.local:8080/openai