apiVersion: gateway.kgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: agentgateway-rbac
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: ingress-gateway

  traffic:
    cors:
      allowOrigins:
      - "*"
      allowHeaders:
      - "*"

    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: "agentgateway.dev"
        audiences:
          - "test.agentgateway.dev"
        jwks:
            inline: |
              {
                "keys": [
                  {
                    "use": "sig",
                    "kty": "EC",
                    "kid": "XhO06x8JjWH1wwkWkyeEUxsooGEWoEdidEpwyd_hmuI",
                    "crv": "P-256",
                    "alg": "ES256",
                    "x": "XZHF8Em5LbpqfgewAalpSEH4Ka2I2xjcxxUt2j6-lCo",
                    "y": "g3DFz45A7EOUMgmsNXatrXw1t-PG5xsbkxUs851RxSE"
                  }
                ]
              }
    authorization:
      action: Allow
      policy:
        matchExpressions:
        - 'mcp.tool.name == "echo"'
        - 'jwt.sub == "test-user" && mcp.tool.name == "add"'
        - 'mcp.tool.name == "printEnv" && jwt.nested.key == "value"'
