apiVersion: gateway.kgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: openai-ratelimit
  labels:
    app: egress-gateway
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: openai
  traffic:
    rateLimit:
      global:
        backendRef:
          name: ratelimit
          namespace: default
          port: 8081
        domain: "api-gateway"
        descriptors:
          - entries:
              - name: user-agent
                expression: 'request.headers["user-agent"]'
            unit: Tokens
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: api-gateway
    descriptors:
      # Rate limit per User-Agent header
      - key: user-agent
        rate_limit:
          unit: hour
          requests_per_unit: 100
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.3
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
spec:
  ports:
  - port: 8081
    name: grpc
    targetPort: 8081
    appProtocol: kubernetes.io/h2c
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  template:
    metadata:
      labels:
        app: ratelimit
        app.kubernetes.io/name: ratelimit
    spec:
      containers:
      - name: ratelimit
        image: docker.io/envoyproxy/ratelimit:3e085e5b
        command: ["/bin/ratelimit"]
        ports:
        - containerPort: 8081
          name: grpc
        - containerPort: 6070
          name: debug
        env:
        - name: USE_STATSD
          value: "false"
        - name: LOG_LEVEL
          value: "debug"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        - name: RUNTIME_IGNOREDOTFILES
          value: "true"
        - name: REDIS_SOCKET_TYPE
          value: "tcp"
        - name: REDIS_URL
          value: "redis:6379"
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-config